location / {
    rewrite ^/post/(.*)\.html$ /post.php?s=$1 last;
    rewrite ^/city/([0-9]+)$ /index.php?city=$1 last;
    rewrite ^/list/([0-9]+)\.html$ /list.php?id=$1 last;
    rewrite ^/hot/(.*)\.html$ /hot.php?k=$1 last;
    rewrite ^/(index\.html|index\.htm|index\.asp|index\.aspx|index\.do)$ /index.php last;
    rewrite ^/sitemap\.xml$ /sitemap.php?st=xml last;
    rewrite ^/sitemap\.txt$ /sitemap.php?st=txt last;

    if ($uri !~* ^/(list/|city/|post/|hot/|open/|sitemap\.|index\.)) {
        rewrite .* /404.php last;
    }
}

location ~* ^/(keys\.seo|gaopin\.seo|kill\.txt|city\.txt|spider\.gif) {
    deny all;
    return 403;
}